---
title: "Script to Generate Data and Plots/Tables for Thesis Simulation 2"
author: "Scott Koeneman"
date: "February 21, 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#For some plotting and organizational features
library(tidyverse)
library(ggplot2)
library(reshape2)
library(nlme)
library(Matrix)
```

# Perform Simulation and Collate Results

```{r, echo=TRUE, message=FALSE, warning=FALSE}

#Set a seed and some other parameters
set.seed(2202023)
library(nlme)
library(tidyverse)
library(Matrix)

#Fixed effects
intercept <- 2
b1 <- 2
b2 <- 2

#Number of observations per subject
m <- 5

#Set up var/covar matrix among observations from one subject
#We will set up simple compound symmetry
sigma_2 <- 8
rho <- 0.5
cov_mat <- sigma_2*matrix(rho,nrow = m, ncol = m)
diag(cov_mat) <- sigma_2
print(cov_mat)

###Make a dataset that encompasses all of candidate models we are going to fit###
#All correlation structures (1 = compound symmetry, 2 = AR(1), 3 = unstructured, 4 = independence)
cor_structs <- c(1,2,3,4)
cor_dof <- c(2,2,(m*(m+1)/2)-m+1,1)
max_cor_dof <- (m*(m+1)/2)-m+1
#All mean structures, presented as formulas
mean_structs <- c("y ~ x1",
                  "y ~ x2",
                  "y ~ x3",
                  "y ~ x1 + x2",
                  "y ~ x1 + x3",
                  "y ~ x2 + x3",
                  "y ~ x1 + x2 + x3")
mean_dof <- c(2,2,2,3,3,3,4)
max_mean_dof <- 4
cand_models <- data.frame(mean_struct = character(length(cor_structs)*length(mean_structs)),
                          cor_struct = numeric(length(cor_structs)*length(mean_structs)),
                          dof = numeric(length(cor_structs)*length(mean_structs)),
                          dof_diff = numeric(length(cor_structs)*length(mean_structs)))
index <- 1
for (ii in 1:length(cor_structs)){
  for (jj in 1: length(mean_structs)){
    cand_models$mean_struct[index] <- mean_structs[jj]
    cand_models$cor_struct[index] <- cor_structs[ii]
    cand_models$dof[index] <- mean_dof[jj] + cor_dof[ii]
    cand_models$dof_diff[index] <- (max_mean_dof+max_cor_dof)-(cand_models$dof[index])
    index <- index + 1
  }
}
#Add columns to track how many times each method selects each model
cand_models$Min_AIC_Select <- numeric(nrow(cand_models))
cand_models$Rule_of_2_Select <- numeric(nrow(cand_models))
cand_models$Stand_AIC_Select <- numeric(nrow(cand_models))

##########################################
### Run simulation to get some results ###
##########################################

num_iters <- 1000

n <- 250
subjects <- n/m

for(jj in 1:num_iters){
  #Generate dataset based on these specifications
  
  dataset <- data.frame(subject = numeric(n), x1 = numeric(n), x2 = numeric(n),
                        y = numeric(n))
  
  for(ii in 1:subjects){
    #Generate fixed effect covariates for this subject
    x1 <- runif(1,0,5)
    x2 <- runif(1,0,5)
    x3 <- runif(1,0,5)
    #Generate outcomes based on correlation structure
    subj_ys <- MASS::mvrnorm(n = 1, mu = (numeric(m)+1)*(intercept+x1*b1+x2*b2),
                             Sigma = cov_mat)
    #Save our generated data
    dataset$subject[((ii*5)-4):(ii*5)] <- ii*(numeric(m)+1)
    dataset$x1[((ii*5)-4):(ii*5)] <- x1*(numeric(m)+1)
    dataset$x2[((ii*5)-4):(ii*5)] <- x2*(numeric(m)+1)
    dataset$x3[((ii*5)-4):(ii*5)] <- x3*(numeric(m)+1)
    dataset$y[((ii*5)-4):(ii*5)] <- subj_ys
    
  }
  #Fit all candidate models
  fit_models <- data.frame(AIC = numeric(nrow(cand_models)),
                           param_diff = cand_models$dof_diff)
  for(ii in 1:nrow(cand_models)){
    if(cand_models$cor_struct[ii] == 1){
      fit <- gls(as.formula(cand_models$mean_struct[ii]), data = dataset,
                 correlation = corCompSymm(form = ~1|subject))
    } else if(cand_models$cor_struct[ii] == 2){
      fit <- gls(as.formula(cand_models$mean_struct[ii]), data = dataset,
                 correlation = corAR1(form = ~1|subject))
    } else if(cand_models$cor_struct[ii] == 3){
      fit <- gls(as.formula(cand_models$mean_struct[ii]), data = dataset,
                 correlation = corSymm(form = ~1|subject))
    } else{
      fit <- gls(as.formula(cand_models$mean_struct[ii]), data = dataset,
                 correlation = corCompSymm(value = 0, form = ~1|subject, fixed = TRUE))
    }
    fit_models$AIC[ii] <- AIC(fit)
  }
  #Do minimum AIC model
  results_Min_AIC <- which.min(fit_models$AIC)
  cand_models$Min_AIC_Select[results_Min_AIC] <- cand_models$Min_AIC_Select[results_Min_AIC] + 1
  #Do rule of 2 + parsimony - models are listed from most parsimonious to least
  cands <- fit_models %>%
    mutate(index = row_number()) %>%
    filter(AIC <= min(fit_models$AIC) + 2) %>%
    arrange(desc(param_diff))
  results_Rule_of_2 <- cands$index[1]
  cand_models$Rule_of_2_Select[results_Rule_of_2] <- cand_models$Rule_of_2_Select[results_Rule_of_2] + 1
  #Do standardized AIC
  ref_AIC <- fit_models$AIC[21]
  fit_models <- fit_models %>%
    mutate(AIC_diff = AIC - ref_AIC) %>%
    mutate(stand_AIC = ifelse(AIC_diff == 0, 0, AIC_diff/sqrt(2*param_diff)))
  cands <- fit_models %>%
    mutate(index = row_number()) %>%
    filter(stand_AIC <= -sqrt(1/2)+2) %>%
    arrange(desc(param_diff))
  results_Standardized_AIC <- cands$index[1]
  cand_models$Stand_AIC_Select[results_Standardized_AIC] <- cand_models$Stand_AIC_Select[results_Standardized_AIC] + 1
}
#Calculate proportions
cand_models$Min_AIC_Select <- cand_models$Min_AIC_Select/num_iters
cand_models$Rule_of_2_Select <- cand_models$Rule_of_2_Select/num_iters
cand_models$Stand_AIC_Select <- cand_models$Stand_AIC_Select/num_iters

print(cand_models)

##########################################
### Run simulation to get some results ###
##########################################

#Clear columns
cand_models$Min_AIC_Select <- numeric(nrow(cand_models))
cand_models$Rule_of_2_Select <- numeric(nrow(cand_models))
cand_models$Stand_AIC_Select <- numeric(nrow(cand_models))

num_iters <- 1000

n <- 500
subjects <- n/m

for(jj in 1:num_iters){
  #Generate dataset based on these specifications
  
  dataset <- data.frame(subject = numeric(n), x1 = numeric(n), x2 = numeric(n),
                        y = numeric(n))
  
  for(ii in 1:subjects){
    #Generate fixed effect covariates for this subject
    x1 <- runif(1,0,5)
    x2 <- runif(1,0,5)
    x3 <- runif(1,0,5)
    #Generate outcomes based on correlation structure
    subj_ys <- MASS::mvrnorm(n = 1, mu = (numeric(m)+1)*(intercept+x1*b1+x2*b2),
                             Sigma = cov_mat)
    #Save our generated data
    dataset$subject[((ii*5)-4):(ii*5)] <- ii*(numeric(m)+1)
    dataset$x1[((ii*5)-4):(ii*5)] <- x1*(numeric(m)+1)
    dataset$x2[((ii*5)-4):(ii*5)] <- x2*(numeric(m)+1)
    dataset$x3[((ii*5)-4):(ii*5)] <- x3*(numeric(m)+1)
    dataset$y[((ii*5)-4):(ii*5)] <- subj_ys
    
  }
  #Fit all candidate models
  fit_models <- data.frame(AIC = numeric(nrow(cand_models)),
                           param_diff = cand_models$dof_diff)
  for(ii in 1:nrow(cand_models)){
    if(cand_models$cor_struct[ii] == 1){
      fit <- gls(as.formula(cand_models$mean_struct[ii]), data = dataset,
                 correlation = corCompSymm(form = ~1|subject))
    } else if(cand_models$cor_struct[ii] == 2){
      fit <- gls(as.formula(cand_models$mean_struct[ii]), data = dataset,
                 correlation = corAR1(form = ~1|subject))
    } else if(cand_models$cor_struct[ii] == 3){
      fit <- gls(as.formula(cand_models$mean_struct[ii]), data = dataset,
                 correlation = corSymm(form = ~1|subject))
    } else{
      fit <- gls(as.formula(cand_models$mean_struct[ii]), data = dataset,
                 correlation = corCompSymm(value = 0, form = ~1|subject, fixed = TRUE))
    }
    fit_models$AIC[ii] <- AIC(fit)
  }
  #Do minimum AIC model
  results_Min_AIC <- which.min(fit_models$AIC)
  cand_models$Min_AIC_Select[results_Min_AIC] <- cand_models$Min_AIC_Select[results_Min_AIC] + 1
  #Do rule of 2 + parsimony - models are listed from most parsimonious to least
  cands <- fit_models %>%
    mutate(index = row_number()) %>%
    filter(AIC <= min(fit_models$AIC) + 2) %>%
    arrange(desc(param_diff))
  results_Rule_of_2 <- cands$index[1]
  cand_models$Rule_of_2_Select[results_Rule_of_2] <- cand_models$Rule_of_2_Select[results_Rule_of_2] + 1
  #Do standardized AIC
  ref_AIC <- fit_models$AIC[21]
  fit_models <- fit_models %>%
    mutate(AIC_diff = AIC - ref_AIC) %>%
    mutate(stand_AIC = ifelse(AIC_diff == 0, 0, AIC_diff/sqrt(2*param_diff)))
  cands <- fit_models %>%
    mutate(index = row_number()) %>%
    filter(stand_AIC <= -sqrt(1/2)+2) %>%
    arrange(desc(param_diff))
  results_Standardized_AIC <- cands$index[1]
  cand_models$Stand_AIC_Select[results_Standardized_AIC] <- cand_models$Stand_AIC_Select[results_Standardized_AIC] + 1
}
#Calculate proportions
cand_models$Min_AIC_Select <- cand_models$Min_AIC_Select/num_iters
cand_models$Rule_of_2_Select <- cand_models$Rule_of_2_Select/num_iters
cand_models$Stand_AIC_Select <- cand_models$Stand_AIC_Select/num_iters

print(cand_models)

##########################################
### Run simulation to get some results ###
##########################################

#Clear columns
cand_models$Min_AIC_Select <- numeric(nrow(cand_models))
cand_models$Rule_of_2_Select <- numeric(nrow(cand_models))
cand_models$Stand_AIC_Select <- numeric(nrow(cand_models))

num_iters <- 1000

n <- 750
subjects <- n/m

for(jj in 1:num_iters){
  #Generate dataset based on these specifications
  
  dataset <- data.frame(subject = numeric(n), x1 = numeric(n), x2 = numeric(n),
                        y = numeric(n))
  
  for(ii in 1:subjects){
    #Generate fixed effect covariates for this subject
    x1 <- runif(1,0,5)
    x2 <- runif(1,0,5)
    x3 <- runif(1,0,5)
    #Generate outcomes based on correlation structure
    subj_ys <- MASS::mvrnorm(n = 1, mu = (numeric(m)+1)*(intercept+x1*b1+x2*b2),
                             Sigma = cov_mat)
    #Save our generated data
    dataset$subject[((ii*5)-4):(ii*5)] <- ii*(numeric(m)+1)
    dataset$x1[((ii*5)-4):(ii*5)] <- x1*(numeric(m)+1)
    dataset$x2[((ii*5)-4):(ii*5)] <- x2*(numeric(m)+1)
    dataset$x3[((ii*5)-4):(ii*5)] <- x3*(numeric(m)+1)
    dataset$y[((ii*5)-4):(ii*5)] <- subj_ys
    
  }
  #Fit all candidate models
  fit_models <- data.frame(AIC = numeric(nrow(cand_models)),
                           param_diff = cand_models$dof_diff)
  for(ii in 1:nrow(cand_models)){
    if(cand_models$cor_struct[ii] == 1){
      fit <- gls(as.formula(cand_models$mean_struct[ii]), data = dataset,
                 correlation = corCompSymm(form = ~1|subject))
    } else if(cand_models$cor_struct[ii] == 2){
      fit <- gls(as.formula(cand_models$mean_struct[ii]), data = dataset,
                 correlation = corAR1(form = ~1|subject))
    } else if(cand_models$cor_struct[ii] == 3){
      fit <- gls(as.formula(cand_models$mean_struct[ii]), data = dataset,
                 correlation = corSymm(form = ~1|subject))
    } else{
      fit <- gls(as.formula(cand_models$mean_struct[ii]), data = dataset,
                 correlation = corCompSymm(value = 0, form = ~1|subject, fixed = TRUE))
    }
    fit_models$AIC[ii] <- AIC(fit)
  }
  #Do minimum AIC model
  results_Min_AIC <- which.min(fit_models$AIC)
  cand_models$Min_AIC_Select[results_Min_AIC] <- cand_models$Min_AIC_Select[results_Min_AIC] + 1
  #Do rule of 2 + parsimony - models are listed from most parsimonious to least
  cands <- fit_models %>%
    mutate(index = row_number()) %>%
    filter(AIC <= min(fit_models$AIC) + 2) %>%
    arrange(desc(param_diff))
  results_Rule_of_2 <- cands$index[1]
  cand_models$Rule_of_2_Select[results_Rule_of_2] <- cand_models$Rule_of_2_Select[results_Rule_of_2] + 1
  #Do standardized AIC
  ref_AIC <- fit_models$AIC[21]
  fit_models <- fit_models %>%
    mutate(AIC_diff = AIC - ref_AIC) %>%
    mutate(stand_AIC = ifelse(AIC_diff == 0, 0, AIC_diff/sqrt(2*param_diff)))
  cands <- fit_models %>%
    mutate(index = row_number()) %>%
    filter(stand_AIC <= -sqrt(1/2)+2) %>%
    arrange(desc(param_diff))
  results_Standardized_AIC <- cands$index[1]
  cand_models$Stand_AIC_Select[results_Standardized_AIC] <- cand_models$Stand_AIC_Select[results_Standardized_AIC] + 1
}
#Calculate proportions
cand_models$Min_AIC_Select <- cand_models$Min_AIC_Select/num_iters
cand_models$Rule_of_2_Select <- cand_models$Rule_of_2_Select/num_iters
cand_models$Stand_AIC_Select <- cand_models$Stand_AIC_Select/num_iters

print(cand_models)

```
