---
title: "Script to Generate Residual Plot for Simulation 5"
author: "Scott Koeneman"
date: "February 24, 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)



#For working with matrices
library(Matrix)
#For some plotting and organizaitonal features
library(tidyverse)
#For working with numbers out to greater precision
library(Rmpfr)
#For Digamma and Trigamma calculation functions
library(PDQutils)
#For arbitrary levels of precision when doing matrix operations
library(gmp)
#Set an initial seed
library(matrixcalc)
library(ggplot2)
library(reshape2)
```

```{r, echo=TRUE, message=FALSE, warning=FALSE}
#Set some initial params
intercept <- 2
b1 <- 1
b2 <- 1
true_sig <- 2

#Draw data
dataset <- data.frame(x = runif(1000,min = 0, max = 5), z = runif(1000,min = 0, max = 5))

#Generate outocomes based on covariates and parameters
dataset$y <- intercept + b1*dataset$x + b2*dataset$z + rnorm(1000, mean = 0,
                                                             sd = true_sig + runif(1000,min = 0, max = 5))
#Fit model and look at residual plots
model <- lm(y ~ x + z, data = dataset)
#Fitted values vs residuals
plot(fitted(model), resid(model))
#Make a nicer plot to output
plot_data <- data.frame(fitted = fitted(model),
                        residuals = resid(model))
ggplot(plot_data, aes(x=fitted, y=residuals)) +
  geom_point() 


```
